### ISSUE TITLE
Incompatible with subfolders

### ISSUE THREAD

**Issue by DaPutzy** [Zweite93/Stalker2PakCfgMergeTool#1]
Currently incompatible with subfolders which includes everyone using Vortex. 

Most likely caused by https://github.com/Zweite93/Stalker2PakCfgMergeTool/blob/1.1.0/Stalker2PakCfgMergeTool/Implementations/Cue4PakProvider.cs#L20. Should probably be `SearchOption.AllDirectories` since Vortex puts all paks into subfolders. Not sure if that change would break something somewhere else though :)

**Comment by Zweite93** [comment]
Should be fixed now.
