### ISSUE TITLE
Virus detected in 2.0.3

### ISSUE THREAD

**Issue by Evanito** [Zweite93/Stalker2PakCfgMergeTool#15]
Most recent release 2.0.3 is flagged as a virus in Windows.

VirusTotal is clean: https://www.virustotal.com/gui/url/3722daa55a316c064d39807682344f93b6f7caf9737b93e9456b598763265ce9?nocache=1

Not sure what you can do about this.

**Comment by Zweite93** [comment]
I know. Just windows being windows.
