### ISSUE TITLE
It doesn't work on xbox game pass version.

### ISSUE THREAD

**Issue by woduseh** [Zweite93/Stalker2PakCfgMergeTool#3]
The path to the exe file for my xbox game pass version is shown below.

```
C:\XboxGames\S.T.A.L.K.E.R. 2\Content\Stalker2\Binaries\WinGDK\Stalker2-WinGDK-Shipping.exe
```

However, in the ```Stalker2PakCfgMergeTool/Program.cs``` file, there doesn't seem to be a case for the above path.

It would be great if this case could be fixed to catch the path as well, thanks.

**Comment by Zweite93** [comment]
So it's Stalker2-WinGDK-Shipping.exe, not Stalker2-WinGDK-Edditor.exe? Some people says it Shipping, some says it's Edditor.

**Comment by Zweite93** [comment]
Try latest release.

**Comment by wickywonka** [comment]
> output "Unexpected error occurred: AES key not found"
var aesKey = AesKeyGetter.Get(Path.Combine(gamePath, exeFilePath)) ?? throw new Exception("AES key not found");
I think, on this step, the "exeFilePath" value is a full path, no need to "Path.Combine"

**Comment by Zweite93** [comment]
@wickywonka this is an issue with game pass version, it has some security cheks that is not allowing AESDupster to grab the key from game's executble. I'm trying to find a fix for that.

**Comment by Zweite93** [comment]
@woduseh fixed in new release.

**Comment by woduseh** [comment]
@Zweite93 Now it works perfectly. Thanks for the quick fix.
