### ISSUE TITLE
not working in my game pass 

### ISSUE THREAD

**Issue by CaraMob323** [Zweite93/Stalker2PakCfgMergeTool#8]
I tried in all folders but nothing works

`C:\XboxGames\S.T.A.L.K.E.R. 2- Heart of Chornobyl (Windows)\Content>Stalker2PakCfgMergeTool "replace_me :)"
The game executable file not found in the provided path.
Please provide the path to the game folder as the first argument.`

`C:\XboxGames\S.T.A.L.K.E.R. 2- Heart of Chornobyl (Windows)\Content\Stalker2\Binaries\WinGDK>Stalker2PakCfgMergeTool "replace_me :)"
The game executable file not found in the provided path.
Please provide the path to the game folder as the first argument.`

**Comment by Zweite93** [comment]
Follow the instructions properly.
