### ISSUE TITLE
It's not clear what to do with original files

### ISSUE THREAD

**Issue by STARasGAMES** [Zweite93/Stalker2PakCfgMergeTool#9]
I used the merge tool, and got the `zzzzz_merged_cfg_modpack_2024-12-01_17-35-10_P.pak`. But what to do next? I have several mods installed using Vortex Mod Manager, and I don't know what `.pak` files I should delete now.

**Comment by Sangeki** [comment]
> I don't know what `.pak` files I should delete now.
None.

1. The merged MOD gets automatically named in a way that makes it load last which means that it has priority and overwrites any prior conflicting files.

2. The other .pak files that are part of the merging process could contain more than just one file. And some of the other files may not conflict.

**Comment by Zweite93** [comment]
![image](https://github.com/user-attachments/assets/92f62c6d-9d53-4672-8087-3bde70410220)
